package org.eclipse.scanning.api.ui.auto;

/**
 * 
 * Create a model editor which is autogenerated user interface for
 * editing models.
 * 
 * This viewer will normally be castable to org.eclipse.jface.viewers.ISelectionProvider
 * in order to add selection listeners.
 * 
 * @author Matthew Gerring
 * @param T the type of the bean for which this is a viewer.
 */
public interface IModelViewer<T> {

	/**
	 * Called to create the part control.
	 * The type U is usually Composite but may be parameterised for non-SWT
	 * 
	 * 
	 * @param ancestor
	 * @return
	 */
	<U> U createPartControl(U ancestor);
	
	
	/**
	 * The model which we are editing
	 * @param model
	 * @throws exception if interface cannot be rendered from this model.
	 */
	void setModel(T model) throws InterfaceInvalidException;

	
	/**
	 * The model which we are editing
	 * @param model
	 */
	T getModel();

    /**
     * Call to dispose 
     */
	void dispose();
	
	/**
	 * Get the underlying Control which the UI system is using.
	 * @return
	 */
	<U> U getControl();
	
	/**
	 * Refresh the table or UI items
	 */
	void refresh();
	
	/**
	 * Make the viewer take focus to its main control.
	 */
	void setFocus();
}
